/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateIncomeVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_VERIFICATION_THRESHOLD"
      | "VERIFICATION_VALIDITY_PERIOD"
      | "compareIncomes"
      | "confidentialProtocolId"
      | "deactivateVerification"
      | "getActiveVerificationCount"
      | "getPendingRequestCount"
      | "getRequestInfo"
      | "getUserRequests"
      | "getUserVerifications"
      | "getVerificationInfo"
      | "isVerificationValid"
      | "processVerificationRequest"
      | "requestCounter"
      | "requestIncomeVerification"
      | "updateVerificationAuthority"
      | "userRequests"
      | "userVerifications"
      | "verificationAuthority"
      | "verificationCount"
      | "verificationRequests"
      | "verifications"
      | "verifyIncomeThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IncomeVerified"
      | "ThresholdVerification"
      | "VerificationExpired"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_VERIFICATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_VALIDITY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "compareIncomes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateVerification",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveVerificationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerifications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerificationValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processVerificationRequest",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestIncomeVerification",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerificationAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userVerifications",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificationRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIncomeThreshold",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_VERIFICATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_VALIDITY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compareIncomes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveVerificationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerificationValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processVerificationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIncomeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIncomeThreshold",
    data: BytesLike
  ): Result;
}

export namespace IncomeVerifiedEvent {
  export type InputTuple = [
    verificationId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish,
    meetsThreshold: boolean
  ];
  export type OutputTuple = [
    verificationId: bigint,
    user: string,
    timestamp: bigint,
    meetsThreshold: boolean
  ];
  export interface OutputObject {
    verificationId: bigint;
    user: string;
    timestamp: bigint;
    meetsThreshold: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdVerificationEvent {
  export type InputTuple = [
    verificationId: BigNumberish,
    user: AddressLike,
    qualified: boolean
  ];
  export type OutputTuple = [
    verificationId: bigint,
    user: string,
    qualified: boolean
  ];
  export interface OutputObject {
    verificationId: bigint;
    user: string;
    qualified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationExpiredEvent {
  export type InputTuple = [verificationId: BigNumberish, user: AddressLike];
  export type OutputTuple = [verificationId: bigint, user: string];
  export interface OutputObject {
    verificationId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateIncomeVerification extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateIncomeVerification;
  waitForDeployment(): Promise<this>;

  interface: PrivateIncomeVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_VERIFICATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VERIFICATION_VALIDITY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  compareIncomes: TypedContractMethod<
    [_verificationId1: BigNumberish, _verificationId2: BigNumberish],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deactivateVerification: TypedContractMethod<
    [_verificationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveVerificationCount: TypedContractMethod<[], [bigint], "view">;

  getPendingRequestCount: TypedContractMethod<[], [bigint], "view">;

  getRequestInfo: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        requester: string;
        isPending: boolean;
        requestTime: bigint;
        documentHash: string;
      }
    ],
    "view"
  >;

  getUserRequests: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserVerifications: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getVerificationInfo: TypedContractMethod<
    [_verificationId: BigNumberish],
    [
      [boolean, boolean, bigint, bigint, string, string] & {
        isVerified: boolean;
        isActive: boolean;
        verificationTime: bigint;
        expiryTime: bigint;
        employerHash: string;
        verifiedUser: string;
      }
    ],
    "view"
  >;

  isVerificationValid: TypedContractMethod<
    [_verificationId: BigNumberish],
    [boolean],
    "view"
  >;

  processVerificationRequest: TypedContractMethod<
    [_requestId: BigNumberish, _employerHash: string, _isApproved: boolean],
    [void],
    "nonpayable"
  >;

  requestCounter: TypedContractMethod<[], [bigint], "view">;

  requestIncomeVerification: TypedContractMethod<
    [
      _incomeLevel: BigNumberish,
      _employmentMonths: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;

  updateVerificationAuthority: TypedContractMethod<
    [_newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  userRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userVerifications: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  verificationAuthority: TypedContractMethod<[], [string], "view">;

  verificationCount: TypedContractMethod<[], [bigint], "view">;

  verificationRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean, bigint, string] & {
        requester: string;
        claimedIncomeLevel: string;
        employmentDuration: string;
        isPending: boolean;
        requestTime: bigint;
        documentHash: string;
      }
    ],
    "view"
  >;

  verifications: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, bigint, bigint, string, string] & {
        encryptedIncomeLevel: string;
        encryptedEmploymentMonths: string;
        isVerified: boolean;
        isActive: boolean;
        verificationTime: bigint;
        expiryTime: bigint;
        employerHash: string;
        verifiedUser: string;
      }
    ],
    "view"
  >;

  verifyIncomeThreshold: TypedContractMethod<
    [_verificationId: BigNumberish, _requiredLevel: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_VERIFICATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_VALIDITY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "compareIncomes"
  ): TypedContractMethod<
    [_verificationId1: BigNumberish, _verificationId2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateVerification"
  ): TypedContractMethod<[_verificationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveVerificationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequestInfo"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        requester: string;
        isPending: boolean;
        requestTime: bigint;
        documentHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRequests"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserVerifications"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVerificationInfo"
  ): TypedContractMethod<
    [_verificationId: BigNumberish],
    [
      [boolean, boolean, bigint, bigint, string, string] & {
        isVerified: boolean;
        isActive: boolean;
        verificationTime: bigint;
        expiryTime: bigint;
        employerHash: string;
        verifiedUser: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerificationValid"
  ): TypedContractMethod<[_verificationId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "processVerificationRequest"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _employerHash: string, _isApproved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestIncomeVerification"
  ): TypedContractMethod<
    [
      _incomeLevel: BigNumberish,
      _employmentMonths: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateVerificationAuthority"
  ): TypedContractMethod<[_newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userVerifications"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verificationAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verificationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verificationRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean, bigint, string] & {
        requester: string;
        claimedIncomeLevel: string;
        employmentDuration: string;
        isPending: boolean;
        requestTime: bigint;
        documentHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifications"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, bigint, bigint, string, string] & {
        encryptedIncomeLevel: string;
        encryptedEmploymentMonths: string;
        isVerified: boolean;
        isActive: boolean;
        verificationTime: bigint;
        expiryTime: bigint;
        employerHash: string;
        verifiedUser: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyIncomeThreshold"
  ): TypedContractMethod<
    [_verificationId: BigNumberish, _requiredLevel: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "IncomeVerified"
  ): TypedContractEvent<
    IncomeVerifiedEvent.InputTuple,
    IncomeVerifiedEvent.OutputTuple,
    IncomeVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdVerification"
  ): TypedContractEvent<
    ThresholdVerificationEvent.InputTuple,
    ThresholdVerificationEvent.OutputTuple,
    ThresholdVerificationEvent.OutputObject
  >;
  getEvent(
    key: "VerificationExpired"
  ): TypedContractEvent<
    VerificationExpiredEvent.InputTuple,
    VerificationExpiredEvent.OutputTuple,
    VerificationExpiredEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "IncomeVerified(uint256,address,uint256,bool)": TypedContractEvent<
      IncomeVerifiedEvent.InputTuple,
      IncomeVerifiedEvent.OutputTuple,
      IncomeVerifiedEvent.OutputObject
    >;
    IncomeVerified: TypedContractEvent<
      IncomeVerifiedEvent.InputTuple,
      IncomeVerifiedEvent.OutputTuple,
      IncomeVerifiedEvent.OutputObject
    >;

    "ThresholdVerification(uint256,address,bool)": TypedContractEvent<
      ThresholdVerificationEvent.InputTuple,
      ThresholdVerificationEvent.OutputTuple,
      ThresholdVerificationEvent.OutputObject
    >;
    ThresholdVerification: TypedContractEvent<
      ThresholdVerificationEvent.InputTuple,
      ThresholdVerificationEvent.OutputTuple,
      ThresholdVerificationEvent.OutputObject
    >;

    "VerificationExpired(uint256,address)": TypedContractEvent<
      VerificationExpiredEvent.InputTuple,
      VerificationExpiredEvent.OutputTuple,
      VerificationExpiredEvent.OutputObject
    >;
    VerificationExpired: TypedContractEvent<
      VerificationExpiredEvent.InputTuple,
      VerificationExpiredEvent.OutputTuple,
      VerificationExpiredEvent.OutputObject
    >;

    "VerificationRequested(uint256,address,uint256)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
